// import { Inter } from "next/font/google";
import { Cinzel_Decorative} from 'next/font/google'
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const CinzelDecorative = Cinzel_Decorative({weight:'700' , style:'normal' , preload:false});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <body className={CinzelDecorative.className}>{children}</body>
  );
}
