// import { Inter } from "next/font/google";
import { Cinzel_Decorative} from 'next/font/google'
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const CinzelDecorative = Cinzel_Decorative({weight:'700' , style:'normal' , preload:false});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className={`${CinzelDecorative.className} relative flex flex-col justify-between items-center min-h-screen ` }>
        <img src={'/bgtop.svg'} alt="Top"  className='absolute top-0 w-full z-0'/>

        {/* {children} Main content goes here */}

        <div className="flex flex-col flex-1 relative z-10">
          {children}
        </div>

        <img src={'/bgbottom.svg'} alt="Bottom"  className="absolute bottom-0 w-full z-0" />
    </div>
  );
}
